name: atlantahamradio
region: atl

static_sites:
  - name: atlantahamradio
    environment_slug: html
    source_dir: /
    error_document: 404.html

    github:                              # ← MUST be "github", not "git"
      repo: discerningowl/atlantahamradio   # ← short username/repo format
      branch: main
      deploy_on_push: true                 # ← this turns auto-deploy on

    routes:
      - path: /

domains:
  - domain: atlantahamradio.org
    type: PRIMARY
    zone: atlantahamradio.org
