name: atlantahamradio
static_sites:
- environment_slug: static-site
  github:
    branch: main
    deploy_on_push: true
    repo: discerningowl/atlantahamradio
  name: atlantahamradio
  error_document: 404.html
